# goreleaser.yml
project_name: geoip
build:
  binary: geoip
  goos:
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
nfpms:
  - homepage: https://github.com/lrstanley/geoip
    maintainer: Liam Stanley <me@liamstanley.io>
    description: GeoIP location service.
    license: MIT
    formats:
      - deb
      - rpm
archives:
  - id: tgz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
release:
  draft: true
snapshot:
  name_template: snapshot-{{.Commit}}
