language: go
go:
- 1.9
- tip
script:
- nvm install stable
- nvm use stable
- nvm current
- make
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.byteirc.org#/dev/null
    template:
    - "%{repository} #%{build_number} %{branch}/%{commit}: %{author} -- %{message}
      %{build_url}"
    on_success: change
    on_failure: change
    skip_join: false
